app/urls.py
"""defines URL patterns for app"""
import datetime
from django.conf.urls import url, include

from haystack.forms import SearchForm
from haystack.query import SearchQuerySet
from . import views
from haystack.views import SearchView, search_view_factory
from .tools import current, today, yesterday
from .forms import ArtSearchForm

sqs = SearchQuerySet().filter(start_date__lte=today).filter(end_date__gte=today)

urlpatterns = [

	url(r'^$', views.index, name='index'),
	url(r'^women/$', views.women, name='women'),
	url(r'^exhibitions/$', views.exhibitions, name='exhibitions'),
	url(r'^movement/(?P<movement_id>[0-9]+)/$', views.movement, name='movement'),
	url(r'^collection/(?P<collection_id>[0-9]+)/$', views.collection, name='collection'),
	url(r'^artist/(?P<artist_id>[0-9]+)/$', views.artist, name='artist'),
	url(r'^search/$', search_view_factory(
		view_class=SearchView, 
		form_class=ArtSearchForm,
		searchqueryset = sqs
	), name='haystack_search'),
	url(r'^about/$', views.about, name='about'),
	url(r'^contact/$', views.contact, name='contact'),
	url(r'^favartist/$', views.favArtist, name='favartist'),
	url(r'^profile/$', views.profile, name='profile'),
]

museum_project/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('allauth.urls')),
    url(r'', include('app.urls', namespace='app')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

app/templates/about.html
{% extends "base.html" %}


{% block content %}
<div>
    <div class="container">
    <div class="row">
        <div class="col-md-3"></div>
        <div class="col-md-6">
	        {% for info in infos %}
            <div class="about" style="background: #000; border-radius: 5px; padding: 15px; color: #ffffff;">
              <br><br>
              <h3>About</h3>
              <p>{{ info.about|linebreaks }}</p>
              <br>
              <p> For further information or answers to any question, feel free to <a href="/contact/">contact us</a>.</p>
            </div>
          {% endfor %}

        </div>
        <div class"col-md-3"></div>    
    </div>
  </div>
</div>

{% endblock content %}

app/templates/artist.html
{% extends "base.html" %}


{% block content %}

    <div class="panel-group">
        <div class="panel panel-default">
            <div class="panel-heading">
                <p class="panel-title">
                    {% if artist.description %}
                        {% if artist.born and artist.nationality %}
                        <a data-toggle="collapse" href="#collapse1">{{ artist }} ({{ artist.nationality }}) b.{{ artist.born }}
                            <span class="glyphicon glyphicon-chevron-down" style="float:right; line-height: 33px"></span>
                        </a>
                        {% elif artist.born %}
                        <a data-toggle="collapse" href="#collapse1">{{ artist }} b.{{ artist.born }}
                            <span class="glyphicon glyphicon-chevron-down" style="float:right; line-height: 33px"></span>
                        </a>
                        {% elif artist.nationality %}
                        <a data-toggle="collapse" href="#collapse1">{{ artist }} ({{ artist.nationality }})
                            <span class="glyphicon glyphicon-chevron-down" style="float:right; line-height: 33px"></span>
                        </a>
                        {% else %}
                        <a data-toggle="collapse" href="#collapse1">{{ artist }}
                            <span class="glyphicon glyphicon-chevron-down" style="float:right; line-height: 33px"></span>
                        </a>
                        {% endif %}
                    {% else %}
                        {% if artist.born and artist.nationality %}
                            {{ artist }} ({{ artist.nationality }}) b.{{ artist.born }}
                        {% elif artist.born %}
                            {{ artist }} b.{{ artist.born }}
                        {% elif artist.nationality %}
                            {{ artist }} ({{ artist.nationality }})
                        {% else %}
                            {{ artist }}
                        {% endif %}
                    {% endif %}
                </p>
            </div>
            {% if artist.description %}
            <div id="collapse1" class="panel-collapse collapse">
                <div class="panel-body"><p>{{ artist.description|linebreaksbr }}</p>
                <p style="text-align: right; padding-right: 20px;"><a href ="https://en.wikipedia.org/wiki/{{artist}}" target='_blank'>From Wikipedia, the free encyclopedia</a></p>
            </div>
                <div class="panel-footer"></div>
            </div>
            {% endif %}
        </div>
    </div>
    <br>

    <form class="search" action="/search/" method="get">
        <input type="search" name="q">
        <input type="submit" value="Search">
    </form>
    <br>
        <div class="counter">
            <p>Results {{ displays.start_index }} - {{ displays.end_index }} of {{ displays.paginator.count }}</p>
        </div>
    <br>

{% if displays %}

    {% for display in displays %}

        <div class="thumbnail" id="artwork">
                                
             <a href ="{{display.pageurl}}" target="_blank">
                <img src="{{display.imageurl}}" style="border:1px solid gray;" alt="{{ display.title|truncatechars:45 }}">
            
                <div class="caption">
                    <h3>{{display.artist}}</h3>
                    <div class="thumb_body">
                        <p>
                        <i>{{display.title|truncatechars:45}}</i></p>

                        {% if display.date is not None %}
                          <p>{{display.date}}</p>
                        {% endif %}

                        <p>
                        {{display.medium|truncatechars:45}}</p>
                        <div class="onviewloc"><p>
                        On view at {{display.collection}}
                        </p></div>
                        {% if user %}
                            {% if display.artist.id not in favoriteartists %}
                                <a href = "javascript:void(0)" class="btn btn-xs btn-success favartistbutton" id="favartist{{display.artist.id}}" data-catid="{{ display.artist.id }}"><span class="glyphicon glyphicon-plus"></span> Favorite Artist</a>
                            {% else %}
                            {% endif %}
                        {% endif %}
                    </div>
                </div>
            </a>
           
        </div>


    {% endfor %}
    <div class="prevnext">
    {% if displays.has_previous %}
            {% if displays.has_previous %}
                <a href="?q={{ query }}&amp;page={{ displays.previous_page_number }}">
                    <button type="button" class="btn btn-default"><< Previous</button>
                </a>
            {% endif %}
    {% endif %}
    {% if displays.has_next %}
            {% if displays.has_next %}
                <a href="?q={{ query }}&amp;page={{ displays.next_page_number }}">
                    <button type="button" class="btn btn-default">Next >></button>
                </a>
            {% endif %}
    {% endif %}
    </div>
{% endif %}


{% endblock content %}

app/templates/base.html
{% load bootstrap3 %}

<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<meta name="description" content="A detailed, searchable index of all artworks on-view at leading art institutions and galleries.">
  		<meta name="keywords" content="Art, Museum, Art Museum, Collection, Painting, Search, Search Engine">

		<title>artnewgo</title>


		{% bootstrap_css %}
		{% bootstrap_javascript %}
		{% load static %}

		<link rel="shortcut icon" href="{% static 'static/favicon.ico' %}" type="image/x-icon">
		<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
		<link href="https://fonts.googleapis.com/css?family=Crimson+Text:400,700%7CKhula:400,700" rel="stylesheet">
		<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>

		
		<script>
  			(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  			(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  			m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  			})(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  			ga('create', 'UA-89877616-1', 'auto');
  			ga('send', 'pageview');
		</script>
	
	</head>
	
	<body style="background: url(http://www.moma.org/media/W1siZiIsIjMzOTExNiJdLFsicCIsImNvbnZlcnQiLCItcmVzaXplIDEwMjR4MTAyNFx1MDAzZSJdXQ.jpg?sha=94a84fac9d759655); background-size:100000px; background-position:center; background-attachment: fixed; padding-bottom: 50px;">

		<nav class="navbar navbar-inverse topnavbar">
		  	<div class="container-fluid">
		    	<div class="navbar-header">
		      		<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
		        		<span class="icon-bar"></span>
		        		<span class="icon-bar"></span>
		        		<span class="icon-bar"></span>
		      		</button>
		      		<a class="navbar-brand" href="{% url 'app:index' %}">art<span style="font-family:Khula; font-weight:700">new</span>go</a>
		    	</div>
        		<div class="collapse navbar-collapse" id="myNavbar">
            		<ul class="nav navbar-nav">
                		<li class="active"><a href="/about">About</a></li>
                		<li>
                    		<a href="#" class="dropdown-toggle" data-toggle="dropdown">Collections<b class="caret"></b></a>
                			<ul class="dropdown-menu">
                				<li>
	                    			{% for collection in collections %}
	                            		{% if collection.collection_name == "MoMA" %}
	                            			<a href="/collection/{{ collection.id }}">{{ collection.collection_name }}</a>
	                            		{% else %}
	                            			<a href="/collection/{{ collection.id }}">{{ collection.collection_name|title }}</a>
	                            		{% endif %}
	                        		{% endfor %}
	                        	</li>
                			</ul>
                		</li>				
						<li>
                    		<a href="#" class="dropdown-toggle" data-toggle="dropdown">Movements<b class="caret"></b></a>
                    		<ul class="dropdown-menu">                       		
                        		<li>
                        			{% for movement in movements %}
                            		<a href="/movement/{{ movement.id }}">{{ movement.movement }}</a>
                        			{% endfor %}
                        		</li>                       
                			</ul>
						</li>
						<li>
                    		<a href="#" class="dropdown-toggle" data-toggle="dropdown">Artists<b class="caret"></b></a>
                    		<ul class="dropdown-menu">	
                        		<li>
                        			{% for artist in artists %}
                            		<a href="/artist/{{ artist.id }}">{{ artist.artist_sans_accents|truncatechars:30 }}</a>
                        			{% endfor %}
                        		</li>
                			</ul>
						</li>
						<li><a href="/women">Women Artists</a></li>
						<li><a href="/exhibitions" style="color: #ff9156;">Current Exhibitions</a></li>
        			</ul>
        			<ul class="nav navbar-nav navbar-right">
						{% if request.user.is_authenticated %}
    						{% if request.user.first_name or request.user.last_name %}
        						<li><a href="/profile"><span class="glyphicon glyphicon-user"></span> {{ request.user.first_name }} {{ request.user.last_name }}</a></li>
    						{% else %}
        						<li><a href="/profile"><span class="glyphicon glyphicon-user"></span> {{ request.user.username }}</a></li>
    						{% endif %}
    						<li><a href="/accounts/logout"><span class="glyphicon glyphicon-log-out"></span> Logout</a></li>
 						{% else %}
 							<li><a href="/accounts/login"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
 						{% endif %}
    				</ul>
        		</div><!--/.nav-collapse -->

			</div>
		</nav>
		<div class="container">
			<div class="page-header">
				{% block header %}
				{% endblock header %}
			</div>
			<div class="main-content">
				{% block content %}
				{% endblock content %}
			</div>
			<div id="footer">Copyright © artnewgo 2017</div>
		</div> <!-- /container -->

		<script type="text/javascript">
	        $('.favartistbutton').click(function(){
	        var catid;
	        artist_id = $(this).attr("data-catid");
	        $.ajax(
	        {
	            type:"POST",
	            url: "/favartist/",
	            data : {
	            	csrfmiddlewaretoken: '{{ csrf_token }}',
	            	artist_id: artist_id,
	            },
			    dataType : "json",
			    success: function( data ){
	                $( '#favartist'+ catid ).remove();
	                $( '#message' ).text(data);
	            }
	         })
	    });
	    </script>
	</body>
</html>

app/templates/collection.html
{% extends "base.html" %}


{% block content %}

    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
    <script type="text/javascript">
      google.charts.load('current', {'packages':['corechart']});
      
      //artist by sex pie chart
      google.charts.setOnLoadCallback(drawSexChart);


      //artist count by movement pie chart
      google.charts.setOnLoadCallback(drawArtistCountMovementChart);

      


      function drawArtistCountMovementChart() {

        var data = google.visualization.arrayToDataTable([
          ['Movement', 'Artworks On View'],
          {% for movement in movement_tally %}
            ['{{ movement.artist__movement__movement }}',     {{ movement.artist__count }}],
          {% endfor %}
          
        ]);

        var options = {
            title: 'Artworks On View by Movement',
            sliceVisibilityThreshold: .03,
            pieSliceText: 'none',
            width: 600,
            height: 400,
        };

        var chart = new google.visualization.PieChart(document.getElementById('movepiechart'));

        chart.draw(data, options);
      }

      function drawSexChart() {

        var data = google.visualization.arrayToDataTable([
          ['Sex', 'Artworks On View'],
          
            ['Female',     {{ female }}],
            ['Male',     {{ male }}],
            ['Unknown',     {{ unknown }}],
          
          
        ]);

        var options = {
          title: "Artworks On View by Artist's Sex",
          pieSliceText: 'none',
          slices: {
            0: { color: 'red' },
            1: { color: 'blue'},
            2: { color: 'transparent' }
          },
          width: 600,
          height: 400,
        };

        var chart = new google.visualization.PieChart(document.getElementById('sexpiechart'));

        chart.draw(data, options);
      }

      // $(window).resize(function(){
      //   drawArtistCountMovementChart();
      //   drawSexChart();
      //   });
    </script>

    <div class="panel-group">
        <div class="panel panel-default">
            <div class="panel-heading">
                <p class="panel-title">
                    <a data-toggle="collapse" href="#collapse1">
                    {% if collection.collection_name == "MoMA" %}
                      {{ collection }}
                    {% else %}
                      {{ collection|title }}
                    {% endif %}
                    <span class="glyphicon glyphicon-chevron-down" style="float:right; line-height: 33px"></span></a>
                </p>
            </div>
            {% if collection.description %}
            <div id="collapse1" class="panel-collapse collapse">
                <div class="panel-body">
                  <p style="text-align: center; font-weight: bold;">{{ collection.address }}</p>
                  <p>{{ collection.description|linebreaksbr }}</p>
                  <p style="text-align: right; padding-right: 20px;"><a href ="https://en.wikipedia.org/wiki/{{collection}}" target='_blank'>From Wikipedia, the free encyclopedia</a></p>

                    <div class="row">
                        <div class="col-6">
                            <div id="movepiechart" class="nomobile"></div>
                        </div>
                        
                    
                        <div class="col-6">
                            <div id="sexpiechart" class="nomobile"></div>
                        </div>
                    </div>

                </div>
                <div class="panel-footer"></div>
            </div>
            {% endif %}
        </div>
    </div>
    <br>

    <form class="search" action="/search/" method="get">
        <input type="search" name="q">
        <input type="submit" value="Search">
    </form>
    <br>
        <div class="counter">
            <p>Results {{ displays.start_index }} - {{ displays.end_index }} of {{ displays.paginator.count }}</p>
        </div>
    <br>
        
{% if displays %}
        {% for display in displays %}
        {% if display.exhibition %}
        <div class="thumbnail" id="exhibition">
            <a href ="{{display.exhibition.pageurl}}" target="_blank">

                <img src="{{display.exhibition.imageurl}}" style="border:1px solid #000;" alt="{{ display.exhibition.title|truncatechars:45 }}">
                <div class="caption">
                    <h4 id="exhibition-title"><i>{{display.exhibition.title|truncatechars:45}}</i></h4>
                    <div class="thumb_body">
                        <ul id="thumb-info-list">
                            {% for artist in display.exhibition.artist.all %}
                                <li><b>{{artist|truncatechars:45}}</b></li>
                            {% endfor %}
                        </ul>
                        <p>{{display.exhibition.description|truncatechars:150}}</p>
                        <div class="onviewloc-exhibit">
                            <p id="exhibition-collection">Current exhibition at <b>{{display.collection}}</b></p>
                        </div>
                    </div>
                </div>
            </a>
        </div>
        {% else %}
                <div class="thumbnail" id="artwork">
                                
             <a href ="{{display.artwork.pageurl}}" target="_blank">
                <img src="{{display.artwork.imageurl}}" style="border:1px solid gray;" alt="{{ display.artwork.title|truncatechars:45 }}">
            
                <div class="caption">
                    <h3>{{display.artwork.artist}}</h3>
                    <div class="thumb_body">
                        <p>
                        <i>{{display.artwork.title|truncatechars:45}}</i></p>
                        {% if display.artwork.date is not None %}
                          <p>{{display.artwork.date}}</p>
                        {% endif %}
                        <p>
                        {{display.artwork.medium|truncatechars:45}}</p>
                        <div class="onviewloc"><p>
                        On view at {{display.artwork.collection}}
                        </p></div>
                        <div class="artist-link">
                            <a href="/artist/{{display.artwork.artist.id}}">More of<br>{{display.artwork.artist}} >></a>
                        </div>
                        {% if user %}
                            {% if display.artwork.artist.id not in favoriteartists %}
                                <a href = "javascript:void(0)" class="btn btn-xs btn-success favartistbutton" id="favartist{{display.artwork.artist.id}}" data-catid="{{ display.artwork.artist.id }}"><span class="glyphicon glyphicon-plus"></span> Favorite Artist</a>
                            {% else %}
                            {% endif %}
                        {% endif %}
                    </div>
                </div>
            </a>
           
        </div>
        {% endif %}
    {% endfor %}
    <div class="prevnext">
    {% if displays.has_previous %}
            {% if displays.has_previous %}
                <a href="?q={{ query }}&amp;page={{ displays.previous_page_number }}">
                    <button type="button" class="btn btn-default"><< Previous</button>
                </a>
            {% endif %}
    {% endif %}
    {% if displays.has_next %}
            {% if displays.has_next %}
                <a href="?q={{ query }}&amp;page={{ displays.next_page_number }}">
                    <button type="button" class="btn btn-default">Next >></button>
                </a>
            {% endif %}
    {% endif %}
    </div>
{% endif %}

{% endblock content %}

app/templates/contact.html
{% extends "base.html" %}

{% block content %}
<div>
    <div class="container">
    	<div class="row">
            <div class="col-md-3"></div>
            <div class="col-md-6" id="contact-forms">
				<h1>Contact</h1>
				<form role="form" action="" method="post">
				    {% csrf_token %}
				    {{ form.as_p }}
				    <button type="submit">Submit</button>
				</form>
			</div>
			<div class="col-md-3"></div>
		</div>
	</div>
</div>
{% endblock content %}

app/templates/exhibitions.html
{% extends "base.html" %}


{% block content %}

    <form class="search" action="/search/" method="get">
        <input type="search" name="q">
        <input type="submit" value="Search">
    </form>
    <br>
        <div class="counter">
            <p>Results {{ displays.start_index }} - {{ displays.end_index }} of {{ displays.paginator.count }}</p>
        </div>
    <br>

{% if displays %}
        {% for display in displays %}
        <div class="thumbnail" id="exhibition">
            <a href ="{{display.pageurl}}" target="_blank">

                <img src="{{display.imageurl}}" style="border:1px solid #000;" alt="{{ display.title|truncatechars:45 }}">
                <div class="caption">
                    <h4 id="exhibition-title"><i>{{display.title|truncatechars:45}}</i></h4>
                    <div class="thumb_body">
                        <ul id="thumb-info-list">
                            {% for artist in display.artist.all %}
                                <li><b>{{artist|truncatechars:45}}</b></li>
                            {% endfor %}
                        </ul>
                        <p id="exhibition-description">{{display.description|truncatechars:100}}</p>
                        <div class="onviewloc-exhibit">
                            <p id="exhibition-collection">Current exhibition at <b>{{display.collection}}</b></p>
                        </div>
                    </div>
                </div>
            </a>
        </div>
        {% endfor %}

    <div class="prevnext">
    {% if display.has_previous %}
            {% if display.has_previous %}
                <a href="?q={{ query }}&amp;page={{ display.previous_page_number }}">
                    <button type="button" class="btn btn-default"><< Previous</button>
                </a>
            {% endif %}
    {% endif %}
    {% if display.has_next %}
            {% if display.has_next %}
                <a href="?q={{ query }}&amp;page={{ display.next_page_number }}">
                    <button type="button" class="btn btn-default">Next >></button>
                </a>
            {% endif %}
    {% endif %}
    </div>
{% endif %}


{% endblock content %}

app/templates/index.html
{% extends "base.html" %}


{% block content %}

    <div class="jumbotron">
    <h2><b>Welcome to </b><span style="color: #ff9156;">art<b>new</b>go</span></h2> 
    <p>A searchable index of <b>artworks and exhibitions currently on view</b> at major collections and galleries.</p>
    </div>

    <form class="search" action="/search/" method="get">
        <input type="search" name="q">
        <input type="submit" value="Search">
    </form>
    <br>
    <br>
    {% if exhibitions %}
        {% for exhibition in exhibitions %}
        <div class="thumbnail" id="exhibition">
            <a href ="{{exhibition.pageurl}}" target="_blank">

                <img src="{{exhibition.imageurl}}" style="border:1px solid #000;" alt="{{ exhibition.title|truncatechars:45 }}">
                <div class="caption">
                    <h4 id="exhibition-title"><i>{{exhibition.title|truncatechars:45}}</i></h4>
                    <div class="thumb_body">
                        <ul id="thumb-info-list">
                            {% for artist in exhibition.artist.all %}
                                <li><b>{{artist|truncatechars:45}}</b></li>
                            {% endfor %}
                        </ul>
                        <p>{{exhibition.description|truncatechars:150}}</p>
                        <div class="onviewloc-exhibit">
                            <p id="exhibition-collection">Current exhibition at <b>{{exhibition.collection}}</b></p>
                        </div>
                    </div>
                </div>
            </a>
        </div>
        {% endfor %}
    {% endif %}
    {% for artwork in artworks %}
    <div class="thumbnail" id="artwork">
        <a href ="{{artwork.pageurl}}" target="_blank">
            <img src="{{artwork.imageurl}}" style="border:1px solid gray;" alt="{{ artwork.title|truncatechars:45 }}">
            <div class="caption">
                <h3>{{artwork.artist|truncatechars:45}}</h3>
                <div class="thumb_body">
                    <ul id="thumb-info-list">
                        <li><b><i>{{artwork.title|truncatechars:45}}</i></b></li>
                        {% if artwork.date is not None %}
                          <li>{{ artwork.date }}</li>
                        {% endif %}
                        <li>{{artwork.medium|truncatechars:45}}</li>
                    </ul>
                    <div class="onviewloc">
                        <p>On view at {{artwork.collection}}</p>
                    </div>
                    <div class="artist-link">
                        <p><a href="/artist/{{artwork.artist.id}}">More of<br>{{artwork.artist}} >></a></p>
                    </div>
                    <div class="movement-link">
                        {% for m in artwork.artist.movement.all %}
                        <a href="/movement/{{ m.id }}">{{ m.movement }} >></a>
                        {% endfor %}
                    </div>
                    {% if user %}
                            {% if artwork.artist.id not in favoriteartists %}
                                <form action="" method="post">
                                    {% csrf_token %}
                                    <button class="btn btn-xs btn-success favartistbutton" id="favartist{{artwork.artist.id}}" data-catid="{{ artwork.artist.id }}"><span class="glyphicon glyphicon-plus"></span> Favorite Artist</button>
                                </form>
                            {% else %}
                            {% endif %}
                    {% endif %}
                </div>
            </div>
        </a>
    </div>
    {% endfor %}

{% endblock content %}

app/templates/new.html
{% extends "base.html" %}


{% block content %}

    <form action="/search/" method="get">
        <input type="text" name="q">
        <input type="search" value="Search">
    </form>
    <br>
    <br>
{% if today %}

{% for artwork in today %}
{% if artwork.accession_number not in yesterday %}

<div class="thumbnail">

     <a href ="{{artwork.pageurl}}" target="blank">
        <img src="{{artwork.imageurl}}" style="border:1px solid gray;">
    
        <div class="caption">
            <h3>{{artwork.artist}}</h3>
            <span class="thumb_body">
                <p>
                <i>{{artwork.title|truncatechars:45}}</i></p><p>
                {{artwork.date}}</p><p>
                {{artwork.medium|truncatechars:45}}</p>
                <div class="onviewloc"><p>
                {{artwork.collection}}
                </p></div>
            </span>
        </div>
    </a>

</div>

{% endif %}
{% endfor %}
{% endif %}

<!-- {% for movement in allmovements %}
    <p>{{ movement }}</p>
{% endfor %} -->

{% endblock content %}

app/templates/profile.html
{% extends "base.html" %}

{% block content %}

<p>{{ user }}</p>
<p>{{ username }}</p>

{% endblock content %}

app/templates/test.html
{% extends "base.html" %}


{% block content %}

    <form action="/search/" method="get">
        <input type="search" name="q">
        <input type="submit" value="Search">
    </form>
    <br>
    <br>
<!-- {% for key, values in artist_by_movement.items %}
    <p>{{ key }}</p>
            <ul>
                {% for artist in values %}
                    <li>{{ artist }}</li>
                {% endfor %}
            </ul>
{% endfor %} -->

<ul class="navbar navbar-nav">
    <li><a href="#" class="dropdown-toggle" data-toggle="dropdown">Movements <b class="caret"></b></a>
        <ul class="dropdown-menu multi-level">
            {% for key, values in artist_by_movement.items %}
                <li class="dropdown-submenu"><a href="">{{ key }}</a>
                    <ul class="dropdown-menu">
                        {% for value in values %}            
                            <li><a href="">{{ value }}</a>
                            </li>
                        {% endfor %}
                    </ul>
                </li>
            {% endfor %}
        <!-- etc. -->
        </ul>
    </li>
</ul>
<!-- {% for movement in allmovements %}
    <p>{{ movement }}</p>
{% endfor %} -->

{% endblock content %}